##This contains all of the basic functions used in the main program for blast alignment.
import numpy as np
import pandas as pd


#Basic steps for BLAST Alignment
#Start with query sequence (q) and heuristics:
#   scoring matrix (M)
#   word length (w)
#   word score threshold (t)
#   segment score threshold (s)

#Steps
#1. Determine words of length w in the sequence q
#2. Compare all words to scoring matrix, return all that score at least t
#2. Scan database for matches from list generated by 2
#3. Extend matches to find high scoring alignments
#4. Return all alignments scoring over S



#FIXME# Change to more descriptive function name
def word_list(q):
    word_list = []

    for i in range(0,len(q)-1):
        word_list.append(q[i:(i+1)])

    return word_list

